### ISSUE TITLE
URL resolve and relative?

### ISSUE THREAD

**Issue by shrinktofit** [cpp-netlib/url#145]
I can't find document about them

**Comment by glynos** [comment]
Hi @shrinktofit, the library design is based on the WhatWG specification. Unlike the RFC3986 document, it does not have steps for URL resolution and relative functions.

The  [examples on the WhatWG URL spec page](https://url.spec.whatwg.org/#example-url-parsing) can give you an idea of how the library should process URLs. In this library, URLs are parsed and processed on construction of the skyr::url object. Furthermore, there is a constructor which takes as an argument a "base" URL, which may give you the behaviour you want.
