### ISSUE TITLE
range/v3/distance.hpp is deprecated

### ISSUE THREAD

**Issue by ysc3839** [cpp-netlib/url#147]
https://github.com/ericniebler/range-v3/blob/86423cfbe537ff3360943bacb9384c53d7447d3d/include/range/v3/distance.hpp#L18-L20
```
RANGES_DEPRECATED_HEADER(
    "This header is deprecated. Please #include <range/v3/iterator/operations.hpp> "
    "instead.")
```

**Comment by glynos** [comment]
This is fixed on main now. Thanks
