### ISSUE TITLE
Support -fno-exceptions

### ISSUE THREAD

**Issue by ingomueller-net** [cpp-netlib/url#18]
I am thinking of using this library in a situation where I have to compile with `-fno-exceptions`. However, this is currently not possible due to the usage of `std::stoull` in `src/ipv4_address.cpp:parse_ipv4_number` (and maybe the usage of `expected`, but I think it has an exception-free variant). For the former issue, [`std::from_chars`](https://en.cppreference.com/w/cpp/utility/from_chars) could be an alternative to `std::stoull`.

**Comment by glynos** [comment]
I like the idea of a no exceptions version of this library, and though I’ve never tested the design should be pretty close to allowing it. However, as you pointed out, unless the dependencies are also possible to compile with exceptions disabled, then I don’t see how to make it work. I may reach out to the author of to::expected.

Your other suggestion is implementable and I would be happy to review a PR.
