### ISSUE TITLE
Incorrect default argument (be_strict) to domain_to_ascii?

### ISSUE THREAD

**Issue by phimuemue** [cpp-netlib/url#36]
Hi there,

as per [WhatWG url spec](https://url.spec.whatwg.org/#concept-domain-to-ascii), we have for "domain to ASCII":

> If beStrict is not given, set it to false

But [`skyr::v1::unicode::domain_to_ascii`](https://github.com/cpp-netlib/url/blob/6219432ebbdca24a29264ee12bde47d35a569dfd/include/skyr/unicode/domain.hpp#L67-L79)  has `true` as a default argument:

https://github.com/cpp-netlib/url/blob/6219432ebbdca24a29264ee12bde47d35a569dfd/include/skyr/unicode/domain.hpp#L67-L79

If I'm not missing anything, this should be `bool be_strict = false`.

I noticed this by trying to urlparse `https://+:80/vroot/` - which fails for netlib/url. Doing the analogue (i.e. JavaScript `new URL("https://+:80/vroot/")`) in Chrome (80.0.3987.132), Firefox (73.0.1), Safari (13.0.5 (15608.5.11)): they all return a new `URL` object.

**Comment by glynos** [comment]
@phimuemue Wow, good catch! And thanks for using the library!

I've applied a fixed and updated a couple of tests in #37 . Could you check that before I merge?

**Comment by phimuemue** [comment]
I think the one in Line 79 (in domain.hpp) is missing.

**Comment by glynos** [comment]
Yeah I already spotted it and pushed a new commit

**Comment by phimuemue** [comment]
Thanks.

Slightly OT: Do you know to what extent this library adheres to the spec? Has it been reviewed or otherwise scrutinized by e.g. a company?

**Comment by glynos** [comment]
I've never had this library reviewed to that level, so I don't know how compliant it is. The spec does evolve so I don't think it's perfectly up-to-date.

Do you know how I could get a more professional review?

**Comment by phimuemue** [comment]
Unfortunately, I do not know this - especially since it is quite a bit of code to examine.
