### ISSUE TITLE
is_url_code_point discrepancy from spec

### ISSUE THREAD

**Issue by phimuemue** [cpp-netlib/url#38]
Hi, https://url.spec.whatwg.org/#url-code-points states:

> The URL code points are ASCII alphanumeric, U+0021 (!), U+0024 ($), U+0026 (&), U+0027 ('), U+0028 LEFT PARENTHESIS, U+0029 RIGHT PARENTHESIS, U+002A (*), U+002B (+), U+002C (,), U+002D (-), U+002E (.), U+002F (/), U+003A (:), U+003B (;), U+003D (=), U+003F (?), U+0040 (@), U+005F (_), U+007E (~), and code points in the range U+00A0 to U+10FFFD, inclusive, excluding surrogates and noncharacters.

But `is_url_code_point` has:

    "!$&'()*+,-./:/=?@_~"

Shouldn't this be like:

    "!$&'()*+,-./:;=?@_~"

I.e. change the second slash (`/`) to a semicolon (`;`).

**Comment by glynos** [comment]
Yep, thanks for catching
