### ISSUE TITLE
Check if host is IP?

### ISSUE THREAD

**Issue by artemyarulin** [cpp-netlib/url#51]
Hi, first of all thank you for such a great library, pure joy to use.

I wonder if there is a functionality to check if host is an IP address. Going through tests I've found https://github.com/cpp-netlib/url/blob/master/tests/url/ipv4_address_tests.cpp#L14 with `skyr::ipv4_address` function, which unfortunately not public as far as I can see. 

What do you about such feature in this library?

**Comment by glynos** [comment]
Thanks for the kind words.

I didn't make those public, but I could. I would like to extend the interface anyway, including easier domain name functionality.

**Comment by glynos** [comment]
@artemyarulin Let me know if the changes in the PR (#52) work for you

**Comment by artemyarulin** [comment]
Hi, thanks - reading modern C++ code is such a pleasure for eyes 😍 

I've noticed that in my code I'm using `skyr::parse` and `url_record`, while you've introduced new helpers to `url`. Am I doing wrong thing or is there a way to convert one to another? 

Thanks again for your help

**Comment by glynos** [comment]
The user documentation isn't quite ready. It's interesting you say you're using url_record directly, I was expecting skyr::url to be the main entry point, and the examples reflect that. What you're not doing isn't wrong though, they're part of the public interface and if that works for you that's good.

There is a constructor of skyr::url that takes a r-value reference to a url_record:

https://github.com/cpp-netlib/url/blob/baa7a4acb5c8d139bf6fcb4c7ec538289a5ac72e/include/skyr/url.hpp#L140

I don't know if that does what you're expecting. Going forward, I'm intending to more functionality to the skyr::url class.
