### ISSUE TITLE
Allow boost::filesystem for macOS compatibility?

### ISSUE THREAD

**Issue by emmenlau** [cpp-netlib/url#91]
I've started to use url and like it quite a lot. However I've hit a blocker problem in that Apple introduced full support for std::filesystem only in macOS 10.15, which very much limits the applicability of url. If I can propose optional support for boost::filesystem, would that be an acceptable merge request?

**Comment by glynos** [comment]
Thanks for the kind comments.

I've been thinking how to allow extending the library. I'd prefer to keep the core to as few dependencies as possible (today, only tl::expected, and optionally nlohmann::json).

However, I would be happy to review a pull request.

**Comment by emmenlau** [comment]
I can certainly relate to your sentiment about a low dependency barrier! If it where not for your beautiful encapsulation of `std::experimental::filesystem` vs `std::filesystem`, I would not have come up with the idea. But with this in place, I am under the impression that a (completely optional) addition of boost::filesystem would cause very little ripples.

My idea would be to add boost::filesystem as little intrusive as possible. I would also suggest to drop it again at some point in the future, when support for c++ std::filesystem is more broadly adopted.

Generally I'm under the impression this is possible except for one issue: in https://github.com/cpp-netlib/url/blob/8847cc7b55a672e67cd076c3b1c161bd4538e3dd/include/skyr/v1/filesystem/path.hpp#L75 there is a use of `path.generic_u8string()` that does not exist in boost::filesystem. boost has a base variant, see https://www.boost.org/doc/libs/1_70_0/libs/filesystem/doc/reference.html#generic_string-template. Is it possible to work with that (and the equivalent `std::filesystem::path::generic_string()`?

**Comment by strega-nil** [comment]
@emmenlau for what it's worth, `generic_string()` is not ever what you want on Windows, since it uses locales; you _need_ to use `generic_u8string()` there.

**Comment by emmenlau** [comment]
Dear @strega-nil thanks a lot for helping! I'm not really into Unicode but I assumed the problem could be solved more easily. I'll try to clarify my train of thought, can you help me understand where I am on the wrong track?

My idea would be to replace the use of `generic_u8string()` (that exists only in std) with `generic_string()` (that exists in std and boost). To preserve the current behavior, this would require to wrap `generic_string()` in a method that emulates whatever `generic_u8string()` does when compared to `generic_string()`.

Ideally such a wrapper could be implemented based on the `unicode` class from this library. But as a basic principle, when looking at https://github.com/microsoft/STL/blob/2c441c7e03dbce45a0048a531af23f7561a25cd4/stl/inc/filesystem#L1026 and https://github.com/microsoft/STL/blob/2c441c7e03dbce45a0048a531af23f7561a25cd4/stl/inc/filesystem#L980 I'm under the impression that `u8string()` is relatively straight-forward? It seems for native Windows char, `u8string()` calls `_Convert_wide_to_narrow<char_traits<_U8Ty>>(__std_code_page::_Utf8, _Text, allocator<_U8Ty>{});` whereas `string()` just returns the chars.

Could therefore a wrapper be implemented that takes the result of `path::string()` and returns the equivalent of `path::u8string()` on all platforms? Or is this the part where I am wrong, where the result of `path::string()` can not be mapped to the equivalent of `path::u8string()` anymore?

Thanks for your advise!

**Comment by strega-nil** [comment]
That is the issue, yes. IMO, the best way forward would be to add a free function:

```cpp
#if STD_FILESYSTEM
std::string generic_string(const stdfs::path& p) {
  return p.generic_u8string();
}
#elseif BOOST_FILESYSTEM
std::string generic_string(const boost:: filesystem::path& p) {
  return p.generic_string();
}
#endif

**Comment by emmenlau** [comment]
Ok, and then boost still needs care to get the utf8-conversion? Something like this?
```cpp
...
#elif BOOST_FILESYSTEM
std::string generic_string(const boost::filesystem::path& p) {
#ifdef _MSC_VER
  return p.generic_string(std::codecvt_utf8());
#else
  return p.generic_string();
#endif
}
#endif
```

**Comment by strega-nil** [comment]
@emmenlau would someone use `boost::filesystem` on Windows? I'd have to do more research on that.

**Comment by strega-nil** [comment]
If someone were to use `boost::filesystem` on Windows, then you'd have to do that same kind of thing for _all_ of the member functions that take a `codecvt`.

**Comment by glynos** [comment]
@emmenlau , I understood your request is to use boost::filesystem on MacOS. I would not try to support this function on Windows if you don't need it.

**Comment by emmenlau** [comment]
I'm not planning to use boost::filesystem on Windows!

But if I'm going to the effort of implementing it, then I'd like to provide means that make it difficult to mis-use it. So in my idea, I would either ensure that the code can not be used on Windows (like an #error in the header), or I'd like to make it safe to use. Currently it looks like making it safe is actually less effort. So this would be my preferred choice. And it may turn out useful in case the same problem comes up in the future again on other platforms. But I'm happy with either of the two choices.

What's your take on this?

**Comment by strega-nil** [comment]
I would argue that making it an error in the CMakeLists.txt is much less effort than making it safe.

**Comment by emmenlau** [comment]
> I would argue that making it an error in the CMakeLists.txt is much less effort than making it safe.

Can you help me understand why that is the case?

**Comment by glynos** [comment]
It's too much effort, and requires quite specialized knowledge. Furthermore, @strega-nil is indicating that no-one should use this function on Windows.

**Comment by strega-nil** [comment]
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b6007580..27b194c8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -24,6 +24,7 @@ option(skyr_BUILD_WITHOUT_RTTI "Build without RTTI." OFF)
 option(skyr_USE_STATIC_CRT "Use static C Runtime library (/MT or MTd)." ON)
 option(skyr_BUILD_WITH_LLVM_LIBCXX "Instruct Clang to use LLVM's implementation of C++ standard library" OFF)
 option(skyr_ENABLE_JSON_FUNCTIONS "Enable functions to convert URL components to JSON" ON)
+option(skyr_USE_BOOST_FILESYSTEM "Use boost::filesystem for filesystem functions" OFF)
 
 set(CMAKE_VERBOSE_MAKEFILE true)
 set(CMAKE_CXX_STANDARD 17)
@@ -41,6 +42,9 @@ if (skyr_USE_STATIC_CRT AND ${CMAKE_CXX_COMPILER_ID} MATCHES MSVC)
     skyr_replace_dynamic_msvcrt_linker_flags()
 endif()
 
+if (skyr_USE_BOOST_FILESYSTEM AND CMAKE_SYSTEM_NAME MATCHES "Windows")
+   message(FATAL_ERROR "boost::filesystem is not supported on windows")
+endif()
 
 add_subdirectory(src)
 ```

**Comment by emmenlau** [comment]
The cmake-only check seems dangerous in my eyes because it encourages misuse. It's easy to remove the check there, and that may lead to broken code that the compiler happily accepts. I usually prefer to explicitly encapsulate the problematic statement with an error and state clearly what may be the problem, so people after me can address it.

But I did not mean to argue, rather to understand the underlying reason. If you prefer, I'll make the code illegal to compile on Windows. I should find some time early next week.

Thanks for all the interesting insights!

**Comment by AlexandreBossard** [comment]
std::filesytem have some broken implementations on early c++17 compilers  (migw-32 in my case). Here's my patch to disable it: 

```diff --git a/CMakeLists.txt b/CMakeLists.txt
index ab167ef8..a4cc1c22 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -24,6 +24,7 @@ option(skyr_BUILD_WITHOUT_RTTI "Build without RTTI." OFF)
 option(skyr_USE_STATIC_CRT "Use static C Runtime library (/MT or MTd)." ON)
 option(skyr_BUILD_WITH_LLVM_LIBCXX "Instruct Clang to use LLVM's implementation of C++ standard library" OFF)
 option(skyr_ENABLE_JSON_FUNCTIONS "Enable functions to convert URL components to JSON" ON)
+option(skyr_ENABLE_FS_FUNCTIONS "Enable filesystem url handling" ON)
 
 set(CMAKE_VERBOSE_MAKEFILE true)
 set(CMAKE_CXX_STANDARD 17)
@@ -66,7 +67,9 @@ endif()
 # Add an alias for projects that use skyr-url as a dependency
 if (NOT CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
     add_library(skyr::skyr-url ALIAS skyr-url)
-    add_library(skyr::skyr-filesystem ALIAS skyr-filesystem)
+    if (skyr_ENABLE_FS_FUNCTIONS)
+      add_library(skyr::skyr-filesystem ALIAS skyr-filesystem)
+    endif()
     if (skyr_ENABLE_JSON_FUNCTIONS)
         add_library(skyr::skyr-json ALIAS skyr-json)
     endif()
@@ -86,7 +89,11 @@ write_basic_package_version_file(
         COMPATIBILITY SameMajorVersion
         ARCH_INDEPENDENT)
 
-set(skyr_TARGETS skyr-url skyr-filesystem)
+set(skyr_TARGETS skyr-url)
+if (skyr_ENABLE_FS_FUNCTIONS)
+  list(APPEND skyr_TARGETS skyr-filesystem)
+endif()
+
 if (skyr_ENABLE_JSON_FUNCTIONS)
     list(APPEND skyr_TARGETS skyr-json)
 endif()
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c0602970..a83624b1 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -157,30 +157,32 @@ target_include_directories(
 # skyr-filesystem
 #################################################
 
-add_library(skyr-filesystem INTERFACE)
+if (skyr_ENABLE_FS_FUNCTIONS)
+    add_library(skyr-filesystem INTERFACE)
 
-target_compile_features(skyr-filesystem INTERFACE cxx_std_17)
+    target_compile_features(skyr-filesystem INTERFACE cxx_std_17)
 
-skyr_check_filesystem(filesystem_definitions)
-target_compile_definitions(
-        skyr-filesystem
-        INTERFACE
-        ${filesystem_definitions}
-)
+    skyr_check_filesystem(filesystem_definitions)
+    target_compile_definitions(
+            skyr-filesystem
+            INTERFACE
+            ${filesystem_definitions}
+    )
 
-target_link_libraries(
-        skyr-filesystem
-        INTERFACE
-        skyr-url
-        $<${gnu}:"stdc++fs">
-)
+    target_link_libraries(
+            skyr-filesystem
+            INTERFACE
+            skyr-url
+            $<${gnu}:"stdc++fs">
+    )
 
-target_include_directories(skyr-filesystem
-        INTERFACE
-        $<INSTALL_INTERFACE:include>
-        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
-        $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include>
-        )
+    target_include_directories(skyr-filesystem
+            INTERFACE
+            $<INSTALL_INTERFACE:include>
+            $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
+            $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include>
+    )
+endif()
 
 #################################################
 # skyr-json
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index f641f174..28c8d6a9 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -37,7 +37,9 @@ add_subdirectory(domain)
 add_subdirectory(percent_encoding)
 add_subdirectory(network)
 add_subdirectory(url)
-add_subdirectory(filesystem)
+if (skyr_ENABLE_FS_FUNCTIONS)
+    add_subdirectory(filesystem)
+endif()
 if (skyr_ENABLE_JSON_FUNCTIONS)
     add_subdirectory(json)
 endif()```

As for using boost filesystem, IMHO you should make it explicit through a cmake option.

**Comment by emmenlau** [comment]
I guess this can be closed now.
